# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.USER_NAME }}
        password: ${{ secrets.PASSWORD }}
        script: |
          cd /root/nodejsPgm/vastusuhasnode
          rm -rf vastusuhas
          git clone git@github.com:sumeetpatil/vastusuhas.git
          cd vastusuhas
          npm install
          npm stop
          npm start